# Generated by Django 3.1.5 on 2021-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210206_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Bouillon'), (1, 'Enligne')]),
        ),
    ]
